apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment

spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app     # find pods with this label to manage

  template:
    metadata:
      labels:
        app: my-app   # create pods with this label
    spec:
      containers:
      - name: my-container
        image: hello-k8s:v2
        ports:
        - containerPort: 3000
        env:
        - name: MESSAGE         # Create environment variable from ConfigMap
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: MESSAGE
      
        - name: API_KEY         # Create environment variable from Secret
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: FAKE_API_KEY
        
